### ISSUE TITLE
HTMLBars vs. React

### ISSUE THREAD

**Issue by jayphelps** [jayphelps/graffiti#1]
Due to some semi-recent changes to React, it's now feasible to use React as the templating/rendering engine instead of HTMLBars. I'm not opposed to this idea although it's not a decision to take lightly. I'm still leaning towards HTMLBars because the average dev is likely more initially comfortable with the mustache-like syntax using helpers.

Please chime in if you have opinions either way.

It would look _something like_ this:

``` jsx
import { registerElement, reflectToAttribute, observe, autobind } from 'graffiti';

@registerElement('my-counter')
class MyCounterComponent {
  @reflectToAttribute()
  counter = 0;
  fontColor = '#000';
  fontSize = 24;

  @observe('counter')
  counterDidChange() {
    console.log('counter', this.counter);
  }

  @autobind    
  increment() {
    this.counter++;
  }

  render() {
    return (
      <element>
        <div id="label"><content></content></div>
        Value: <span id="counterVal">{this.attributes.counter.value}</span><br/>
        <button onClick={this.increment}>Increment</button>
      </element>
    );
  }
}
```

**Comment by RoyTinker** [comment]
Personally, I'm uncomfortable with React's markup because it can't be parsed directly by a JS interpreter. It also harks back to (and might even be parsed with errors in older Firefox versions as) E4X.

If the template needs to live in the same file as code, I would prefer a DSL that conforms syntactically to JavaScript. But I think a modularized approach might be more preferable, where templates live in a separate file with a different extension -- dojo takes this approach to great effect.

**Comment by jayphelps** [comment]
@TimTheTinker I had similar qualms about React's JSX syntax at first..but I've warmed up to it. Also note that all your JS has to be transpiled by Babel anyways since graffiti uses ES7+ syntax. Babel supports JSX out of box, [here's an example](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=import%20%7B%20registerElement%2C%20reflectToAttribute%2C%20observe%2C%20autobind%20%7D%20from%20'graffiti'%3B%0A%0A%40registerElement%28'my-counter'%29%0Aclass%20MyCounterComponent%20%7B%0A%20%20%40reflectToAttribute%28%29%0A%20%20counter%20%3D%200%3B%0A%20%20fontColor%20%3D%20'%23000'%3B%0A%20%20fontSize%20%3D%2024%3B%0A%0A%20%20%40observe%28'counter'%29%0A%20%20counterDidChange%28%29%20%7B%0A%20%20%20%20console.log%28'counter'%2C%20this.counter%29%3B%0A%20%20%7D%0A%0A%20%20%40autobind%20%20%20%20%0A%20%20increment%28%29%20%7B%0A%20%20%20%20this.counter%2B%2B%3B%0A%20%20%7D%0A%0A%20%20render%28%29%20%7B%0A%20%20%20%20return%20%28%0A%20%20%20%20%20%20%3Celement%3E%0A%20%20%20%20%20%20%20%20%3Cdiv%20id%3D%22label%22%3E%3Ccontent%3E%3C%2Fcontent%3E%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20Value%3A%20%3Cspan%20id%3D%22counterVal%22%3E%7Bthis.attributes.counter.value%7D%3C%2Fspan%3E%3Cbr%2F%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7Bthis.increment%7D%3EIncrement%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Felement%3E%0A%20%20%20%20%29%3B%0A%20%20%7D%0A%7D&stage=0)

Obviously that example doesn't "work" because graffiti isn't loaded nor is React's rendering engine, just showing that the syntax parsing itself isn't an issue.

I'm still in the general boat of preferring to keep my templates separate from the JavaScript class declaration since components are view-controllers and I've definitely been in plenty of cases at companies where we all wanted our designers to edit the templates but not touch the business logic. Not all designers can or are willing to learn JavaScript well enough to be "trusted" IMO but that's one of the basic "React vs. Traditional" argument that we could all argue about. It comes down to personal preferences at this point, so I'm open to it if others want it instead of HTMLBars.

**Comment by RoyTinker** [comment]
Also, a couple of thoughts regarding dependencies:
- Depending on React could make Graffiti more or less dependent on, or at least associated with, the future of an entire framework; and generally, frameworks seem to rise and fall more quickly than focused tools such as HTMLBars.
- Depending on non-ES Babel features makes Babel more of a compilation target than a stopgap transpiler... which might also affect the longevity of Graffiti when ES6/7 are fully supported across browsers and (hopefully) Babel ends or moves on to focusing on early support of ES8+.

Those might be worth considering depending on what your goals for Graffiti are.

**Comment by jayphelps** [comment]
@TimTheTinker very valid points indeed!

**Comment by RoyTinker** [comment]
Also, the way you describe Web Components as a framework Kumbaya, Graffiti might do better (and help more) being framework-agnostic. :-)

**Comment by jayphelps** [comment]
@TimTheTinker Agreed--I imagine that if we went down the React-as-an-engine path that work would be done to work with the React team to extract _just_ its rendering engine out and maintain as a separate project, though I can easily see Facebook wouldn't be down for that for various reasons.

**Comment by jayphelps** [comment]
Definitely not going down the React path. There are other vdom implementations that are attractive, however. But at this time I'm so far along with HTMLBars with the Glimmer changes and things are looking pretty dang good. Thanks for the input!
